-- Insert real challenges with proper UUIDs and valid constraint values
INSERT INTO public.challenges (
  id,
  title,
  description,
  challenge_type,
  target_value,
  target_unit,
  start_date,
  end_date,
  difficulty_level,
  reward_points,
  genres,
  is_featured,
  is_public,
  booktok_themed
) VALUES 
(
  gen_random_uuid(),
  '52 Books Challenge',
  'Read 52 books in one year - one book per week!',
  'books',
  52,
  'books',
  '2025-01-01',
  '2025-12-31',
  'hard',
  500,
  ARRAY['fantasy', 'romance', 'mystery', 'sci-fi'],
  true,
  true,
  false
),
(
  gen_random_uuid(),
  'Romance February',
  'Read 4 romance novels this February and fall in love with love!',
  'books',
  4,
  'books',
  '2025-02-01',
  '2025-02-28',
  'easy',
  100,
  ARRAY['romance'],
  true,
  true,
  true
),
(
  gen_random_uuid(),
  'Fantasy Quest',
  'Embark on epic adventures by reading 10 fantasy books',
  'books',
  10,
  'books',
  '2025-01-15',
  '2025-06-15',
  'medium',
  250,
  ARRAY['fantasy'],
  true,
  true,
  false
),
(
  gen_random_uuid(),
  'Page Turner',
  'Read 1000 pages this month',
  'pages',
  1000,
  'pages',
  '2025-01-01',
  '2025-01-31',
  'medium',
  150,
  ARRAY['mystery', 'thriller'],
  false,
  true,
  false
),
(
  gen_random_uuid(),
  'BookTok Favorites',
  'Discover 6 trending BookTok recommendations',
  'books',
  6,
  'books',
  '2025-01-01',
  '2025-03-31',
  'easy',
  120,
  ARRAY['romance', 'fantasy', 'ya'],
  true,
  true,
  true
);