-- Insert real challenges with proper UUIDs
INSERT INTO public.challenges (
  id,
  title,
  description,
  challenge_type,
  target_value,
  target_unit,
  start_date,
  end_date,
  difficulty_level,
  reward_points,
  genres,
  is_featured,
  is_public,
  booktok_themed
) VALUES 
(
  gen_random_uuid(),
  '52 Books Challenge',
  'Read 52 books in one year - one book per week!',
  'books_read',
  52,
  'books',
  '2025-01-01',
  '2025-12-31',
  'hard',
  500,
  ARRAY['fantasy', 'romance', 'mystery', 'sci-fi'],
  true,
  true,
  false
),
(
  gen_random_uuid(),
  'Romance February',
  'Read 4 romance novels this February and fall in love with love!',
  'books_read',
  4,
  'books',
  '2025-02-01',
  '2025-02-28',
  'easy',
  100,
  ARRAY['romance'],
  true,
  true,
  true
),
(
  gen_random_uuid(),
  'Fantasy Quest',
  'Embark on epic adventures by reading 10 fantasy books',
  'books_read',
  10,
  'books',
  '2025-01-15',
  '2025-06-15',
  'medium',
  250,
  ARRAY['fantasy'],
  true,
  true,
  false
),
(
  gen_random_uuid(),
  'Page Turner',
  'Read 1000 pages this month',
  'pages_read',
  1000,
  'pages',
  '2025-01-01',
  '2025-01-31',
  'medium',
  150,
  ARRAY['mystery', 'thriller'],
  false,
  true,
  false
),
(
  gen_random_uuid(),
  'BookTok Favorites',
  'Discover 6 trending BookTok recommendations',
  'books_read',
  6,
  'books',
  '2025-01-01',
  '2025-03-31',
  'easy',
  120,
  ARRAY['romance', 'fantasy', 'ya'],
  true,
  true,
  true
);

-- Insert some popular books
INSERT INTO public.books (
  id,
  title,
  authors,
  description,
  genres,
  cover_url,
  page_count,
  published_date,
  average_rating,
  ratings_count,
  is_trending,
  booktok_tags,
  google_books_id
) VALUES 
(
  gen_random_uuid(),
  'Fourth Wing',
  ARRAY['Rebecca Yarros'],
  'Enter the brutal and elite war college, where dragon riders are forged and the weak don''t survive to graduation.',
  ARRAY['fantasy', 'romance', 'new-adult'],
  'https://books.google.com/books/content?id=placeholder&printsec=frontcover&img=1&zoom=1',
  500,
  '2023-05-02',
  4.5,
  125000,
  true,
  ARRAY['dragon-riders', 'enemies-to-lovers', 'military-academy'],
  'placeholder_id_1'
),
(
  gen_random_uuid(),
  'It Ends with Us',
  ARRAY['Colleen Hoover'],
  'A powerful story about love, hope, and the courage it takes to move forward.',
  ARRAY['romance', 'contemporary', 'drama'],
  'https://books.google.com/books/content?id=placeholder&printsec=frontcover&img=1&zoom=1',
  376,
  '2016-08-02',
  4.2,
  89000,
  true,
  ARRAY['emotional', 'tear-jerker', 'romance'],
  'placeholder_id_2'
),
(
  gen_random_uuid(),
  'The Seven Husbands of Evelyn Hugo',
  ARRAY['Taylor Jenkins Reid'],
  'Reclusive Hollywood icon Evelyn Hugo finally decides to tell her life story.',
  ARRAY['historical-fiction', 'lgbtq', 'drama'],
  'https://books.google.com/books/content?id=placeholder&printsec=frontcover&img=1&zoom=1',
  400,
  '2017-06-13',
  4.6,
  156000,
  true,
  ARRAY['old-hollywood', 'lgbtq', 'secrets'],
  'placeholder_id_3'
);

-- Insert some daily quests
INSERT INTO public.daily_quests (
  id,
  title,
  description,
  quest_type,
  target_value,
  reward_points,
  difficulty,
  genres,
  expires_at,
  is_active
) VALUES 
(
  gen_random_uuid(),
  'Read 30 Minutes',
  'Spend at least 30 minutes reading today',
  'reading_time',
  30,
  20,
  'easy',
  ARRAY[]::text[],
  CURRENT_DATE + INTERVAL '1 day',
  true
),
(
  gen_random_uuid(),
  'Finish a Chapter',
  'Complete at least one full chapter today',
  'chapters_read',
  1,
  15,
  'easy',
  ARRAY[]::text[],
  CURRENT_DATE + INTERVAL '1 day',
  true
),
(
  gen_random_uuid(),
  'Fantasy Adventure',
  'Read 50 pages of a fantasy book',
  'pages_read',
  50,
  30,
  'medium',
  ARRAY['fantasy'],
  CURRENT_DATE + INTERVAL '1 day',
  true
);