// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibnnrymvynbtpdqrlckz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlibm5yeW12eW5idHBkcXJsY2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDU3OTUsImV4cCI6MjA3Mjc4MTc5NX0.NqgAQWg65d49Ge-4Rr8vSCBwOedx2OYxG5LPfdLk3kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});